import { Form } from './Form'
import { Login } from './Login'
import { Register } from './Register'
import { Profile } from './Profile'
import { ForgotPassword } from './ForgotPassword'
import { ResetPassword } from './ResetPassword'
import { EventList } from './EventList'
import { EventCard } from './EventCard'
import { UserAvatar as Avatar } from './Avatar'
export const VUser = { Form, Login, Register, Profile, Avatar, EventList, EventCard, ForgotPassword, ResetPassword }